export const LOGIN = 'LOGIN';
export const REQUESTING = 'REQUESTING';
export const REQUESTED = 'REQUESTED';
export const UPDATE_USER = 'UPDATE_USER';
export const LOGOUT = 'LOGOUT';

export const UPDATE_PAGINATION = 'UPDATE_PAGINATION';
export const UPDATE_TUTORS = 'UPDATE_TUTORS';
export const UPDATE_TAGS = 'UPDATE_TAGS';
export const UPDATE_SPECIALIZATIONS = 'UPDATE_SPECIALIZATIONS';
